- id: doi:10.13016/dspace/tbvg-9is5
  type: paper
  description: Srijal's Thesis, which discusses work on ReZoom from 2021-2023.
  date: 2023-6-23
  image: images/scooter_with_sensors_highlighted.jpg

- id: doi:none1
  title: Graph-based Global Path Planning for an Autonomous Electric Scooter using Historical Ride Data
  authors:
    - Vibhu Agrawal
    - Srijal Shekhar Poojari
    - Derek A. Paley
  date: 2023-3-01
  link: pdfs/Graph-based-Global-Path-Planning-for-an-Autonomous-Electric-Scooter-using-Historical-Ride-Data.pdf
  publisher: Unpublished
  type: unpublished
  image: images/historical_scooter_data.png

- id: doi:none2
  title: Analysis and Optimization of Servicing Logistics for Self-Driving E-scooters
  authors:
    - Hao Da Dong
    - Derek A. Paley
  date: 2021-4-14
  link: pdfs/analysis_and_optimization_for_e-scooters.pdf
  publisher: Unpublished
  type: unpublished
  image: images/overview_of_old_approach.jpg

  